#159 Add SSL certificate support (#168)
* Prepare next release

* 17: Read certificate from container

* #159: Add integration tests

* #159: Pad fingerprint with leading 0 if necessary

* #159: Improve test stability

Don't verify log timestamps when checking bucketfs startup

* #159: Refactoring: use Optional instead of checking for Exception

* #159: Review findings

* Use error message builder, add unit tests

* Add documentation for TLS certificates

* 159: Make error codes unique

* Adapt tests for Linux

* Use JDBC url with fingerprint only with version >= 7

Test with 6 fails:

[ERROR] com.exasol.containers.tls.TlsConnectionIT  Time elapsed: 127.078 s  <<< ERROR!
org.testcontainers.containers.ContainerLaunchException: Container startup failed
Caused by: org.rnorth.ducttape.RetryCountExceededException: Retry limit hit with exception
Caused by: org.testcontainers.containers.ContainerLaunchException: Could not create/start container
Caused by: org.testcontainers.containers.ContainerLaunchException: F-ETC-5: Exasol container start-up timed out trying connection to 'jdbc:exa:localhost:49205;validateservercertificate=0' using query 'SELECT 1 FROM DUAL'. Last connection exception was: 'Could not create new connection'
Caused by: java.sql.SQLException: Could not create new connection
Caused by: com.exasol.jdbc.ConnectFailed: Certificates do not conform to algorithm constraints

* Adapt tests for running under linux

* Use message builder, code cleanup

* Bugfix: add padding when first byte of fingerprint is zero

* Adapt tests

* Increase connection timeout to avoid sporadic test failures

Caused by: org.testcontainers.containers.ContainerLaunchException: Could
not create/start container
	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:523)
	at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:329)
	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81)
	... 68 more
Caused by: org.testcontainers.containers.ContainerLaunchException:
F-ETC-5: Exasol container start-up timed out trying connection to
'jdbc:exa:localhost/c0a73371b6cc917420308963d21ecd1c16ae5074f786c6c8e2238e8146b69f46:49154;validateservercertificate=1'
using query 'SELECT 1 FROM DUAL'. Last connection exception was: 'Could
not create new connection'
	at com.exasol.containers.ExasolContainer.waitUntilStatementCanBeExecuted(ExasolContainer.java:628)
	at com.exasol.containers.ExasolContainer.waitUntilContainerStarted(ExasolContainer.java:489)
	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:466)
	... 70 more
Caused by: java.sql.SQLException: Could not create new connection
	at org.testcontainers.containers.JdbcDatabaseContainer.createConnection(JdbcDatabaseContainer.java:228)
	at com.exasol.containers.ExasolContainer.isConnectionAvailable(ExasolContainer.java:641)
	at com.exasol.containers.ExasolContainer.waitUntilStatementCanBeExecuted(ExasolContainer.java:616)
	... 72 more
Caused by: com.exasol.jdbc.ConnectFailed: Remote host terminated the
handshake
	at com.exasol.jdbc.AbstractEXAConnection.setupConnection(AbstractEXAConnection.java:1527)
	at com.exasol.jdbc.AbstractEXAConnection.Connect(AbstractEXAConnection.java:1374)
	at com.exasol.jdbc.AbstractEXAConnection.<init>(AbstractEXAConnection.java:533)
	at com.exasol.jdbc.EXAConnection.<init>(EXAConnection.java:37)
	at com.exasol.jdbc.EXADriver.connect(EXADriver.java:232)
	at org.testcontainers.containers.JdbcDatabaseContainer.createConnection(JdbcDatabaseContainer.java:219)
	... 74 more

* Upgrade dependencies

* Implement review findings

* Add sonarlint mapping

* Use exaError builder for exception

* Update release date

* Review findings: delete empty lines

* Implement Review finding: simplify if statement

* Skip failing test with version <= 7

Timeout for upload is 60s and maybe not enough for the new 6.2.12 version

2021-09-24 07:44:43.537 [SEVERE ] Timeout waiting for object 'drivers/jdbc/dummy_driver_a6cfaf75-5a35-4089-8fa8-cbb94e503b0c.jar' to be synchronized in bucket 'bfsdefault/default' after 2021-09-24T07:43:43.447Z.
2021-09-24 07:44:43.542 [FINE   ] Skipping support package creation. Exit type is EXIT_SUCCESS, monitoring EXIT_NONE
Error:  Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 124.689 s <<< FAILURE! - in com.exasol.drivers.ExasolDriverManagerIT
2021-09-24 07:44:46.800 [INFO   ] Docker instance reuse requested, but this is not supported by Exasol version below 7. Using normal mode instead.
Error:  testInstallDriver{Path}  Time elapsed: 60.173 s  <<< ERROR!
com.exasol.drivers.DriverManagerException: Unable to upload database driver. JDBC driver "DUMMY_DRIVER" (org.example.DummyDriver), source: "/tmp/junit8617072127150869054/dummy_driver_a6cfaf75-5a35-4089-8fa8-cbb94e503b0c.jar"
2021-09-24 07:44:46.801 [FINE   ] Exposing ports: [8888, 6583, 443]
	at com.exasol.drivers.ExasolDriverManager.uploadDriver(ExasolDriverManager.java:71)
2021-09-24 07:44:46.801 [INFO   ] Creating container for image: exasol/docker-db:6.2.16-d1
	at com.exasol.drivers.ExasolDriverManager.installDriver(ExasolDriverManager.java:50)
	at com.exasol.drivers.ExasolDriverManager.install(ExasolDriverManager.java:42)
	at com.exasol.drivers.ExasolDriverManagerIT.testInstallDriver(ExasolDriverManagerIT.java:45)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:688)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6(TestMethodTestDescriptor.java:210)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:206)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:131)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:65)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:220)
	at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$6(DefaultLauncher.java:188)
	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:202)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:181)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:128)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:150)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:124)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
Caused by: java.util.concurrent.TimeoutException: Timeout waiting for object 'drivers/jdbc/dummy_driver_a6cfaf75-5a35-4089-8fa8-cbb94e503b0c.jar' to be synchronized in bucket 'bfsdefault/default' after 2021-09-24T07:43:43.447Z.
	at com.exasol.bucketfs.SyncAwareBucket.waitForFileToBeSynchronized(SyncAwareBucket.java:121)
	at com.exasol.bucketfs.SyncAwareBucket.uploadFile(SyncAwareBucket.java:43)
	at com.exasol.drivers.ExasolDriverManager.uploadDriver(ExasolDriverManager.java:67)
	... 68 more

Co-authored-by: jakobbraun <jakob.braun@posteo.de>