Use JDBC url with fingerprint only with version >= 7
Test with 6 fails:

[ERROR] com.exasol.containers.tls.TlsConnectionIT  Time elapsed: 127.078 s  <<< ERROR!
org.testcontainers.containers.ContainerLaunchException: Container startup failed
Caused by: org.rnorth.ducttape.RetryCountExceededException: Retry limit hit with exception
Caused by: org.testcontainers.containers.ContainerLaunchException: Could not create/start container
Caused by: org.testcontainers.containers.ContainerLaunchException: F-ETC-5: Exasol container start-up timed out trying connection to 'jdbc:exa:localhost:49205;validateservercertificate=0' using query 'SELECT 1 FROM DUAL'. Last connection exception was: 'Could not create new connection'
Caused by: java.sql.SQLException: Could not create new connection
Caused by: com.exasol.jdbc.ConnectFailed: Certificates do not conform to algorithm constraints